---
title: "R Notebook"
output: html_notebook
---

```{r, message=FALSE, warning=FALSE}
library(tidyverse)

df2016 = read_csv("TestScores2016_RegEd.csv")
df2015 = read_csv("TestScores2015_RegEd.csv")
df2014 = read_csv("TestScores2014_RegEd.csv")

full_dataframe <- rbind(df2016,df2015,df2014)
```

```{r, message=FALSE, warning=FALSE}

df_long = gather(full_dataframe, key, value, `3-Math-Advanced`:`EOI-EnglishIII-Satisfactory`) %>%
  separate_("key", into = c("Grade", "Subject", "Level"), sep = "-") %>%
  spread( Level, value)


df_long_full = filter(df_long, !is.na(df_long$Satisfactory))


```


```{r}
df_long_full$Advanced = as.numeric(df_long_full$Advanced)

df_long_full$Satisfactory = as.numeric(df_long_full$Satisfactory)

glimpse(df_long_full)
```

```{r}
df_long_full$Advanced = df_long_full$Advanced * df_long_full$Satisfactory

df_long_full$Satisfactory = df_long_full$Satisfactory - df_long_full$Advanced

df_long_full$Below_Satisfactory = 1 - (df_long_full$Satisfactory + df_long_full$Advanced)

View(df_long_full)
```
```{r}

df_wide = gather(df_long_full, key, value, Advanced:Below_Satisfactory)

df_wide$key = paste(df_wide$Grade, df_wide$Subject, df_wide$key, sep ="-")

df_wide = df_wide[c("Year","SchoolCode","Site","key","value")]

df_wide = spread(df_wide,key, value)

write.csv(df_wide, "school_test_scores(14-16).csv")
```

