---
title: "R Notebook"
output:
  word_document: default
  pdf_document: default
  html_notebook: default
---

```{r message=FALSE, warning=FALSE, include=FALSE, paged.print=FALSE}
library(knitr)
library(tidyverse)
library(xtable)
library(kableExtra)
library(papeR)
```

```{r, message=FALSE, warning=FALSE}
af = read_csv("final_project_data/AF_Data.csv")
des = read_csv("final_project_data/Descriptors_Census.csv")
des$Yr = as.factor(des$Yr)
des$FallEnrollment = as.double(des$FallEnrollment)
des2 = des[,c(-1,-2,-3,-4)]
```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}

kable(summary(des2[,c(1,2,3,4,6)]), 
      format = "markdown",
      booktabs=T,
      digits = 2, 
      row.names = FALSE, 
      col.names = c("Average Income","Average Property Value /ADM", "Unemployment Rate","Poverty Rate","% Free & Reduced Lunch"),
      caption = "Summary Statistics for OEQA Report",
      escape = TRUE,
      format.args = list(decimal.mark = ".", big.mark = ",")) %>% kable_styling(position = 'center')

```

```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
kable(
    summary(des2[,c("SpEdTeachersFTE","CounselorsFTE","OtherStaffFTE","AdministratorsFTE")]), 
      format = "markdown",
      booktabs=T,
      digits = 2, 
      row.names = FALSE, 
      col.names = c("FTE Special Education Teachers",
"FTE Counselors",
"FTE Other Staff",
"FTE Administrators"),
      caption = "Summary Statistics for OEQA Report",
      escape = TRUE,
      format.args = list(decimal.mark = ".", big.mark = ","))




```
```{r echo=FALSE, message=FALSE, warning=FALSE, paged.print=FALSE}
kable(
    summary(des2[,c("NonSpEdTeachers", "AvgTeacherSalary","AdvancedDegrees","AvgYrsExperience")]), 
      format = "markdown",
      booktabs=T,
      digits = 2, 
      row.names = FALSE, 
      col.names = c("% Non Special Education Teachers",
"Average Teacher Salary",
"% with Advanced Degrees",
"Average Years Experience"),
      caption = "Summary Statistics for OEQA Report",
      escape = TRUE,
      format.args = list(decimal.mark = ".", big.mark = ","))
```

```{r}
colnames(af)
```
```{r}
kable(
    summary(af[,c("IndexScore", "ELA_GrowthIndex","Math_GrowthIndex","Overall_GrowthIndex")]), 
      format = "markdown",
      booktabs=T,
      digits = 2, 
      row.names = FALSE, 
      col.names = c("Index Score",
"Reading Growth Index",
"Math Growth Index",
"Overall Growth"),
      caption = "Summary Statistics for A-F Data (Selected)t",
      escape = TRUE,
      format.args = list(decimal.mark = ".", big.mark = ","))
```
```{r message=FALSE, warning=FALSE, paged.print=TRUE}
enroll = read_csv("final_project_data/Enrollment.csv")
colnames(table)
```


```{r}
kable(
    summary(enroll[,c("Hispanic%", "NativeAmerican%","Asian%","AfricanAmerican%","PacificIslander%", "White%", "TwoRaces%", "Total")]), 
      format = "markdown",
      booktabs=T,
      digits = 2, 
      row.names = FALSE, 
      col.names = c("% Hispanic",
"% Native American",
"% Asian",
"% African American",
"% Pacific Islander",
"% White",
"% Two or More Races",
"Total"),
      caption = "Summary Statistics Demographics",
      escape = TRUE,
      format.args = list(decimal.mark = ".", big.mark = ","))
```

